### ISSUE TITLE
Enhance machine configuration with internet type

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb_benchmarks#1]
At a minimum, it could be an interactive CLI prompt asking the user to self-describe the internet connection they are current using

Though I'd really prefer it if we could in any way shape or form grab an identifier if possible

```python
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("8.8.8.8", 80))
ip_address = s.getsockname()[0]
s.close()
```

might do the trick? But perhaps we should still ask the user if they are OK with us grabbing and recording that info?

**Comment by rly** [comment]
Perhaps this would be useful https://pypi.org/project/ifcfg/

**Comment by CodyCBakerPhD** [comment]
@oruebel mentioned maybe only the MAC address is the important thing

And to protect privacy we should only store a hash or encrypted string of that value to keep it unique but still identifiable/distinguishable from other result submitters
