### ISSUE TITLE
A new benchmarking platform

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/nwb_benchmarks#16]
We do use asv too but recently discovered

An interesting new benchmarking CI/portal: https://codspeed.io/ which seems to be really easy to use - https://docs.codspeed.io/benchmarks/python   - just pytest `mark` some unittests to be your benchmarks. it is all based on https://pypi.org/project/pytest-benchmark/ so - quite available locally. 

So might be worth considering IMHO and do research first

**Comment by oruebel** [comment]
Thanks @yarikoptic we'll take a look! Currently we are targeting mainly benchmarks for cloud access and some of the tests may have fairly long runtimes (at least compared to standard unit test). At first glance, I think codspeed.io may be more appropriate for benchmarks based on our existing unit tests in PyNWB. I think that would be useful too, but that would target a different use case (i.e., local performance and smaller/faster tests)

**Comment by yarikoptic** [comment]
ideally, if up to it, would be great also to see benchmarking of setups with local caching where on first run the solution (like fsspec) establishes local cache, and then on subsequent rerun uses local content (likely first checking ETag on remote URL to remain the same)... but might be something to really keep for future investigations ;-)

**Comment by oruebel** [comment]
> ideally, if up to it, would be great also to see benchmarking of setups with local caching

We are currently adding ``fsspec + disk cache`` and ``remfile + disk cache`` test. The current tests clean up the cache between runs, so we only see the impact of the cache within the context of the specific operation. It may be interesting to also add tests where we run the test case first in the setup to prime the cache and then evaluate how long it takes to repeat the same operation after the cache has been set up. I'll make a separate issue for this so we can discuss there.
