### ISSUE TITLE
LindiFileReadRemoteReferenceFileSystemContinuousSliceBenchmark fails

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb_benchmarks#57]
Running the following 

```nwb_benchmarks run --bench time_remote_slicing.LindiFileReadRemoteReferenceFileSystemContinuousSliceBenchmark --debug```

fails with an error on teardown with an [Error code 3221225477](https://www.google.com/search?q=error+code+3221225477&sca_esv=3cb57a3b0b929ed3&sca_upv=1&rlz=1C1ONGR_enUS1105US1105&sxsrf=ACQVn0_C_RZ-m8nspIGsJAwmeeU8Iq9IQA%3A1714490459876&ei=WwwxZoyVNcXcptQPx76tmAI&ved=0ahUKEwjMrtPWnuqFAxVFrokEHUdfCyMQ4dUDCBA&uact=5&oq=error+code+3221225477&gs_lp=Egxnd3Mtd2l6LXNlcnAiFWVycm9yIGNvZGUgMzIyMTIyNTQ3NzIIEAAYgAQYogQyCBAAGKIEGIkFSMMlUI8BWN0kcAJ4AZABAJgBZ6ABowiqAQQxMy4xuAEDyAEA-AEBmAIPoALyB8ICChAAGLADGNYEGEfCAgQQIxgnmAMAiAYBkAYIkgcEMTQuMaAH8CQ&sclient=gws-wiz-serp), which traces back to some kind of access violation in memory. 

This error appears to occur only when slicing into a dataset with LINDI. Since `asv` is running tests in a process, maybe this is related to an issue of how LINDI is interacting with processes? 

See also here for more details https://github.com/NeurodataWithoutBorders/nwb_benchmarks/pull/53#issuecomment-2085707609

**Comment by CodyCBakerPhD** [comment]
Note it's not an error caught by Python, to my knowledge, just an error code passed via the `stderr` of the spawned subprocess environment
