### ISSUE TITLE
Missing ndx-mies namespace error

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb_benchmarks#68]
I tried running the benchmark from the current dev branch and am seeing the following errors: 

```
https://dandi-api-staging-dandisets.s3.amazonaws.com/blobs/8b1/f9e/8b1f9e4e-c5bb-4c25-acee-3c99327aa841     data_00002_AD0                        (slice(0, 30000, None),)                       failed   
```

fails with ``KeyError: "'ndx-mies' not a namespace"``. Maybe this is because the `load_namespaces=True`` option was removed? Several other tests (probably for the same file) fail with the same error.

**Comment by rly** [comment]
@oruebel please recreate your environment. the newest pynwb automatically loads namespaces (and the new environment points to particular versions of pynwb, hdmf, and lindi)
