### ISSUE TITLE
Establish specific dandiset to store test files

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb_benchmarks#7]
Instead of linking out to various assets scattered across DANDI, it might make the most sense to centralize all our NWB testing files to a single dandiset to make them easier to identify

Note that in many cases they could have originated with source files found on DANDI, in which case we can count ours as a derived dataset (our derivation being alternative chunking and compression, for instance)

**Comment by oruebel** [comment]
Agreed! Having a DANDIset for performance tests would be great.

**Comment by CodyCBakerPhD** [comment]
@oruebel A good experience for a first time DANDI user: could you add the NOSI grant info as a 'dandiset contribute' in the metadata (type: 'Funder')?

**Comment by CodyCBakerPhD** [comment]
The Dandisets are [000717 ](https://dandiarchive.org/dandiset/000717?pos=1) and [000719](https://dandiarchive.org/dandiset/000719?pos=2)
